### ISSUE TITLE
hint to include plugins in pelicanconf.py

### ISSUE THREAD

**Issue by kika21** [pelican-plugins/search#12]
Please include a hint to include plugins=['search'] in the README.MD

- [x] I have searched the [issues](https://github.com/pelican-plugins/search/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

**Comment by justinmayer** [comment]
The reason that the `PLUGINS` setting is not explicitly mentioned in the Search plugin README is that the `PLUGINS` setting is entirely optional and not needed to use the Search plugin.

As covered in the [Plugins section of the Pelican docs](https://docs.getpelican.com/en/latest/plugins.html), Pelican 4.5+ is designed to auto-discover and register Pip-installed namespace plugins such as the Search plugin. Because the `PLUGINS` setting was required for previous Pelican versions, some folks still have that setting defined and don't understand that the presence of that setting _disables_ the namespace plugin auto-discovery mechanism, and thus those folks need to either remove the `PLUGINS` setting or manually add `search` to that list.

While I believe this is all quite adequately explained in the aforementioned [Plugins section of the Pelican docs](https://docs.getpelican.com/en/latest/plugins.html), perhaps we could modify the Search plugin README with brief guidance and a link to those docs, in an effort to guide folks who might already have the `PLUGINS` setting defined.

**Comment by maphew** [comment]
Ahh, thanks for this clarification! It's an easy situation to run into when one's install and learning path starts at the plugin (or in my case a theme) which haas the desired functionality rathre than Pelican proper.nI think this means that until namespace plugins eclipse the old method all of them will need to have a similar paragraph to the one Justin showed in the PR above.

@justinmayer I can do that busywork if you wish?

**Comment by justinmayer** [comment]
Very kind of you to offer, Matt. Since I already wrote the text to generate the diff I posted to your PR, I'm happy to just go ahead push that now. Thanks again for being so willing to help out! 💕
