### ISSUE TITLE
demo website ?

### ISSUE THREAD

**Issue by ebanDev** [pelican-plugins/search#8]
- [x] I have searched the [issues](https://github.com/pelican-plugins/search/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the documentation and believe that my question is not covered.
- [ ] I am willing to lend a hand to help implement this feature.  (well, ATM I don't have time, but in a few week why not)

## Feature Request

Hello ! It could be cool to have a demo site for this plugin ! :D

**Comment by justinmayer** [comment]
Rather than take the time and energy (which are in short supply) to create a dedicated demo site for this plugin, I have added to the README a short list of sites that use this plugin, which I believe should address this issue even better than a demo site.

**Comment by ebanDev** [comment]
Thanks !! :D

**Comment by maphew** [comment]
It would be useful to have a known-to-work site repo that could be cloned and run locally. This could also serve as a demo (and maybe also as a test suite during plugin development?)

Why? See #20. I've encountered a problem and I don't know if it's because I've stumbled on a bug or if there's something wrong in how I've installed the plugin and integrated it into the theme I'm using.
